### ISSUE TITLE
error on installing plugin in qgis 3.10.3

### ISSUE THREAD

**Issue by ThomasStruller** [alexbruy/processing-whitebox#27]
Can't install the plugin via zip-file install. Got following error-message:

Konnte Erweiterung 'processing-whitebox-master' nicht laden 

ModuleNotFoundError: No module named 'processing_whitebox' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing-whitebox-master\__init__.py", line 28, in 
    from processing_whitebox.whiteboxProviderPlugin import WhiteboxProviderPlugin
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing_whitebox'

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.10.3-A Coruña A Coruña, 0e1f846438

**Comment by alexbruy** [comment]
There were quite a lot of similar tickets, please check bugtracker before creating yet another invalid report.
